name: Build
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: protoc/3.12.3
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/protoc
          tags: "3.12.3"
          path: protoc/3.12.3

      - name: upload
        run: |
          docker login -u $username -p $password
          ./upload.sh quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0 $username/nginx-ingress-controller:0.32.0
          ./upload.sh quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.29.0 $username/nginx-ingress-controller:0.29.0
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
